name: tes_crud
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.2.1+1
  http: ^1.1.0
  shimmer: 2.0.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  flutter_easyloading: 3.0.5
  just_the_tooltip: 0.0.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

